name: Deploy to EC2

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      ec2-host:
        required: true
        type: string
      ec2-user:
        required: true
        type: string
      ec2-key:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      EC2_KEY: ${{ secrets.EC2_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ inputs.ec2-host }}
          username: ${{ inputs.ec2-user }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ inputs.docker-image }}
            docker stop loans-api || true
            docker rm loans-api || true
            docker run -d -p 80:80 --name loans-api ${{ inputs.docker-image }}
