name: Build .NET Project

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Manually Install .NET 9.0 Preview
        run: |
          wget https://download.visualstudio.microsoft.com/download/pr/123456/dotnet-sdk-9.0.0-preview.6-linux-x64.tar.gz -O dotnet-sdk.tar.gz
          mkdir -p $HOME/dotnet
          tar -xzf dotnet-sdk.tar.gz -C $HOME/dotnet
          echo "$HOME/dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
