name: Build Docker Image

on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      service-name:
        required: true
        type: string

jobs:
  build-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Image for specific service using Docker Compose
        run: |
          # Build the Docker image for the specific service using docker-compose.yml and docker-compose.override.yml
          docker-compose -f docker-compose.yml -f docker-compose.override.yml build ${{ inputs.service-name }}

          # List the images
          docker ps
          docker images

          # Tag the built image with the final tag specified in inputs
          docker tag ${{ inputs.service-name }}:latest ${{ inputs.docker-tag }}
