name: Build Docker Image

on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        run: docker build -t ${{ inputs.docker-tag }} -f ${{ inputs.working-directory }}/Dockerfile .
